export const ADD_USER = 'ADD_USER';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_ERROR = 'ADD_USER_ERROR';

export const DELETE_USER = 'DELETE_USER';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_ERROR = 'DELETE_USER_ERROR';

export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_SUCCESS ='FETCH_USER_SUCCESS';
export const FETCH_USER_ERROR ='FETCH_USER_ERROR';

export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USERS_SUCCESS ='FETCH_USERS_SUCCESS';
export const FETCH_USERS_ERROR ='FETCH_USERS_ERROR';

export const MODIFY_USER = 'MODIFY_USER';
export const MODIFY_USER_SUCCESS = 'MODIFY_USER_SUCCESS';
export const MODIFY_USER_ERROR = 'MODIFY_USER_ERROR';
